### ISSUE TITLE
Битая ссылка при попытке перейти на сайт для чтении книги онлайн.

### ISSUE THREAD

**Issue by ydakuka** [shhavel/soabp-online#1]
Hello there. Книгу нельзя больше прочитать онлайн (http://ukrmap.su/en-ruby/index.html), могли бы Вы перенести ее в условно-бесплатные сервисы, например, gitbook.com? Если у Вас нет для этого времени, то могу этим заняться, если Вы не против.

**Comment by shhavel** [comment]
Спасибо, я постараюсь восстановить ссылку http://ukrmap.su/en-ruby/index.html
Если нужно, книга доступна на [github](https://github.com/shhavel/service-oriented-architecture-in-practice-book)
